Runbot depends on base_setup module
Install Runbot raised the following error:

    ParseError: "External ID not found in the system: base.menu_config" while parsing /opt/odoo/additional_addons/odoo-extra/runbot/res_config_view.xml:52, near
    <menuitem id="menu_runbot_configuration" name="Runbot" parent="base.menu_config" sequence="19" action="action_runbot_configuration"/>